### ISSUE TITLE
How did you come with the Magic name?

### ISSUE THREAD

**Issue by gsoldateli** [moiseh/wp-magic-crud#1]
Great nomenclature =)

**Comment by gsoldateli** [comment]
CRUD's FTW

**Comment by moiseh** [comment]
Thanks mate,

At the time this small project solves a lot of P.I.T.A. to me when creating WordPress simple cruds.

So, i not remember exactly when and why the magic's name came but it reflects the feeling that the pain of this project solved to me, of creating WP Cruds with almost NO code =)

Have a great day
